### ISSUE TITLE
bitfuncs.inc missing

### ISSUE THREAD

**Issue by jeng** [sbelectronics/h8#3]
I'm getting this error when building "monitor-8251-master.p":

`> > > monitor.asm(14):21: error: error in opening file`

It looks like the include directory `INC=/home/smbaker/projects/pi/h8/h8-8008/as/include` is missing from the repo.

**Comment by sbelectronics** [comment]
This actually came from the as assembler. I've resolved it today by creating a minimal bitfuncs.inc with only the two functions that are necessary. I've also added a README with some minimal notes on where to get AS from, for those who might need help getting started assembling. Let me know how it works for you... Scott.
